### ISSUE TITLE
scripts를 통한 빌드가 되지 않습니다.

### ISSUE THREAD

**Issue by elrion018** [soaple/create-stickyboard-app#1]
* OS : Window
* node version : 12.16.3
* npm version : 6.14.7

* program doesn't build with 'npm run dev'. downloading packages with 'npm install', many vulnerabilities are found(about 98 vulnerabilities ). Maybe I guess that program doesn't build because transfiling wasn't work associated with these vulnerabilities and webpack config. 

![버전](https://user-images.githubusercontent.com/41279460/89265584-aec3c180-d66f-11ea-9d99-befd69f15436.PNG)
![캡처2](https://user-images.githubusercontent.com/41279460/89265591-b1261b80-d66f-11ea-8366-11eb6f363b55.PNG)
![캡처3](https://user-images.githubusercontent.com/41279460/89265597-b2efdf00-d66f-11ea-9de7-4768a09bfbd6.PNG)

**Comment by soaple** [comment]
I fixed the problem.

Can you try again and let me know the result?

**Comment by elrion018** [comment]
All vulnerabilities were removed.

But still program doesn't work.

The same bug with Image 2 is appeared

**Comment by elrion018** [comment]
In window, you should install 'cross-env' package.

1. npm install cross-env
2. find 'dev' of scripts in package.json file.
3. change string of 'dev' to "cross-env NODE_ENV=development NODE_PATH=./src WEBPACK_DEV_SERVER_MODE=true node app.js"
4. npm run dev

Now, you can build program normally!
